### ISSUE TITLE
Installation guide bin path

### ISSUE THREAD

**Issue by jhamel2** [vaklinov/zcash-swing-wallet-ui#1]
In the following part of the installation guide : 

> Installing the built ZCash GUI wallet
> 
> Assuming you have already installed ZCash in directory /home/user/zcash/bin (for example) which contains the command line tools zcash-cli and zcashd you need to take the created file ./build/jars/ZCashSwingWalletUI.jar and copy it to diretcory /home/user/zcash/bin (the same dir. that contains zcash-cli and zcashd). Example copy command:

You should replace "**/home/user/zcash/bin**" with "**/home/user/zcash/src**" which is the default installation folder as of now.

Keep up the good work!

**Comment by vaklinov** [comment]
Fixed.
