### ISSUE TITLE
The Eclipse .classpath hardcodes the minor JDK version

### ISSUE THREAD

**Issue by zlatinb** [vaklinov/zcash-swing-wallet-ui#10]
This is minor, but annoying.  In .classpath the version of the JDK is hardcoded to
`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/jdk1.8.0_74"/>`

Changing that to 
`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>`
should make it work with whatever version of the jdk is installed.

**Comment by vaklinov** [comment]
Fixed in the Git master branch.
