### ISSUE TITLE
Feature request - ability to specify location of zcashd/zcash-cli

### ISSUE THREAD

**Issue by zlatinb** [vaklinov/zcash-swing-wallet-ui#11]
@radix42 and I are working on building an OSX package that installs the ZCash daemon and the Swing UI without the user having to do any kind of manual configuration.  In order to do this, we're going to need the ability to pass the locations of zcashd and zcash-cli.  I'm thinking something along the lines of a command-line option:

`-Dzcash.location=/Applications/ZCash`

**Comment by vaklinov** [comment]
Change is in the Git master branch: https://github.com/vaklinov/zcash-swing-wallet-ui/commit/153b69c349ca7ed46be7b891f2fe9f4f6bae1a7e

The JVM system property used is named zcash.location.dir. May be used as JVM parameter in the form:
-Dzcash.location.dir=/Users/ivan/ZCash/zcash/src

Please check if this works for you...

**Comment by zlatinb** [comment]
Works great, thanks!
