### ISSUE TITLE
Create a branch that works with Zero

### ISSUE THREAD

**Issue by Optiminer** [vaklinov/zcash-swing-wallet-ui#23]
Zero is a fork of Zcash with better equihash parameters (https://bitcointalk.org/index.php?topic=1796036.0). Create a fork of your wallet that supports Zero.

I would support this with donations. Contact me at optiminer@tutamail.com if you are interested.

**Comment by vaklinov** [comment]
A ZERO GUI wallet already exists: https://github.com/vaklinov/zero-swing-wallet-ui

**Comment by Optiminer** [comment]
Oh, great! Just sent 100 Zero to your donation address!
