### ISSUE TITLE
How to move a wallet

### ISSUE THREAD

**Issue by TylorRoss** [vaklinov/zcash-swing-wallet-ui#5]
any chance you can quickly tell me how to move my wallet from ubuntu VM ---broken front end--- to new stable real ubuntu on ssd...??
i can get the folders open...i just need to know what to move where?

**Comment by vaklinov** [comment]
The GUI wallet is a JAR file (ZCashSwingWalletUI.jar) you can move it from one Ubuntu to another as you would move any other file (e.g. via scp or [WinSCP](https://winscp.net/eng/docs/ui_commander)). If you wish to move the whole ZCash installation - it s more complicated. Your actual ZCash wallet file is `~/.zcash/wallet.dat` and you may move it as a file when ZCash is **not** runing.
