### ISSUE TITLE
Lock file

### ISSUE THREAD

**Issue by TylorRoss** [vaklinov/zcash-swing-wallet-ui#6]
I fricking copyed the wallet while server was running.....rebuilding block chain error..

looked for all locked files..and root folders created by my noobness....

I just want to clean install with no f^%$&N errors....  I know this is not a wallet question but you seem nice enough to put the real answer out there since you are a wallet guru.
im sure its a sudo problem, lock file, or not making a clean install over a directory I forgot to delete...that may have been root privileges....24 hours into this mistake...

It appears that zcash has been started but is not ready to accept wallet connections....
it is still loading the blockchain

**Comment by vaklinov** [comment]
If you copied the wallet.dat while zcashd was running and now zcashd does not start (rebuilding block chain error) then perhaps it is best to try to start zcashd with a new/fresh wallet.dat - to make sure it starts. Then the more difficult task would be to salvage any funds you had in the old wallet.dat (sadly I am not an expert on this).

If zcashd refuses to start even with a fresh wallet.dat maybe it is best to delete all ZCash stuff (back it up first) and install from scratch. I have found that installing the [binary packages](https://github.com/zcash/zcash/wiki/Debian-binary-packages) works fine on Ubuntu...
