### ISSUE TITLE
balance value at "Own addresses" tab

### ISSUE THREAD

**Issue by kye001** [vaklinov/zcash-swing-wallet-ui#7]
I had 2 incomings to the same t-addr. At the "Overwiev" tab is correct balance shown (sum), but balance at "Own addresses" tab shows only value of first income to that particular t-address.
Thanks for your attention,
Yuriy

**Comment by kye001** [comment]
Correction: After restarting, GUI shows correct balance, so it seems, it not update balance field "on fly"...

**Comment by vaklinov** [comment]
The "Own addresses" tab has a Refresh button at the bottom right - the tab does not refresh automatically. Did you try the refresh button?

For now I assume there is no bug. I will accept the issue as a feature request to add automatic refresh to the "Own addresses" tab (to be like the overview tab - automatic).

**Comment by kye001** [comment]
Thanks a lot! 

14 ноября 2016, 21:39:27, от "vaklinov" < notifications@github.com >: 

The "Own addresses" tab has a Refresh button at the bottom right - the tab does not refresh automatically. Did you try the refresh button? For now I assume there is no bug. I will accept the issue as a feature request to add automatic refresh to the "Own addresses" tab (to be like the overview tab - automatic). —

**Comment by vaklinov** [comment]
Automatic refresh of the "Own addresses" tab is now available in the latest version 0.41 (for now available as Github source only - needs to be built).

**Comment by kye001** [comment]
Thanks! 

18 ноября 2016, 21:50:21, от "vaklinov" < notifications@github.com >: 

Automatic refresh of the "Own addresses" tab is now available in the latest version 0.41 (for now available as Github source only - needs to be built). —
