### ISSUE TITLE
Feature request - Debian/Ubuntu packages

### ISSUE THREAD

**Issue by zlatinb** [vaklinov/zcash-swing-wallet-ui#9]
Hi,

I have no problems building from source but it would help adoption if there were packages for Debian and/or Ubuntu.  Then the swing wallet can be included in the official ZCash repo and become the defacto standard wallet UI.

I'm willing to donate 2.0 ZEC to have such packages provided ;-)

Z

**Comment by vaklinov** [comment]
Having Debian/Ubuntu packages is a good idea. However until and unless Zooko and the ZCash company wish to make this wallet the "official ZCash GUI wallet" the packages will be of little value - the user will have to install them separately. He might as well just take a binary GUI wallet release from GitHub... Zooko and the ZCash company know about this wallet, but do not seem interested for now...

The tool to use for packaging could be: https://github.com/tcurdt/jdeb/blob/master/docs/ant.md

**Comment by zlatinb** [comment]
Even if ZCash company does not want to make them the "official" UI, there is still some value in having such packages - mainly the ability to automatically resolve dependencies (i.e. OpenJDK and ZCash itself) and clean updates.

**Comment by vaklinov** [comment]
The latest Git/master version now builds a DEB package:
./build/ubuntu-package/ZCashSwingWalletUI.deb
I have tested it on Ubuntu 16.04. Should also work on Debian but I have not tested. The DEB package deploys two files:
```
/usr/lib/zcash-gui-wallet/ZCashSwingWalletUI.jar
/usr/bin/zcash-swing-wallet-ui
```

I would invite you to try it ;-)

Regarding:
_I'm willing to donate 2.0 ZEC to have such packages provided ;-)_
You may send the ZEC as a targeted donation (for this feature) to T address:
```
t1geZBhbGCn5WbEHjeDh8ASnGfn4UAoGhNX
```

**Comment by zlatinb** [comment]
The 2 ZEC have been sent, txid c51ce3fc562c4fa238d0dfc49fd2c350670dc1051490567b0fd7fcdb92b9b36e

btw on my branch I've added an ant target to build an OSX app bundle, you may be interested in merging it.

**Comment by vaklinov** [comment]
Thank you so much.

I am going to consider you Mac OS changes probably next week. Sorry that I have been rather busy lately (I still am) and I can devote little time to this...
